on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-typescript:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Test Local Action
        uses: ./
        with:
          gitHubToken: "{{ secrets.GITHUB_TOKEN }}"